### ISSUE TITLE
Issue: APK Installation Affects Both Main and Secondary Accounts in Devices with Dual Messenger Functionality

### ISSUE THREAD

**Issue by WingCH** [Hamza417/Inure#224] opened 2023-08-20 10:01 UTC
**Describe the bug**
Some mobile devices support functionalities similar to Android's "work profile", such as Samsung's [dual messenger](https://www.samsung.com/nz/support/mobile-devices/dual-messenger/). I've noticed that when using Inure's install APK feature, the APK gets installed on both the main and secondary accounts. However, I only want to install it on the main account.

To specify a particular user with the APK command, you can try the following:

```
adb install -r --user 12 app_name.apk
```

**To Reproduce**
1. Open a device with multiple account functionality (e.g., Samsung's Dual Messenger).
2. Download the APK file you wish to install
3. Install the APK file using Inure's install APK feature. (i enabled Shizuku)
4. Check both the main and secondary accounts, and you will find the APK has been installed on both.

**Expected behavior**
only want to install it on the main account (current account)

**Smartphone (please complete the following information):**
 - Device: Samsung Fold 4
 - OS:  AOSP Android 13 (One UI 5.1)
 - Version: build99-full (Play Store)

**Comment by Ab-Mr** [comment] 2023-08-23 00:07
Until there is an update, the command secret can be used
 
command 1
 
```shell

``` pm list users

This is to know the names of the users

pm install --user /data/local/tmp/aShell.apk

**Comment by Ab-Mr** [comment] 2023-08-23 00:48
Until there is an update, the command line can be used

This is to know the names of the users
command 1
 
```shell
pm list users
``` 
![Screenshot_20230823-002038_aShell](https://github.com/Hamza417/Inure/assets/93873156/9077e1b5-0929-4efd-a137-20b2977c9ee3)
Transfer apk to /data/local/tmp/ In this command
command 2
```shell
cp /sdcard/magisk.apk /data/local/tmp/
``` 
![Screenshot_20230823-004257_aShell](https://github.com/Hamza417/Inure/assets/93873156/6cef2b5c-47d1-4708-8327-d98818b5d701)
Select the user ID you want
command 3
```shell
pm install --user 0
```
![Screenshot_20230823-004338_aShell](https://github.com/Hamza417/Inure/assets/93873156/091e97b4-8f33-4584-b274-ba7ae3e6225f)
`Note` Always choose path /data/local/tmp/magisk.apk

**Comment by Hamza417** [comment] 2023-08-28 06:40
Inure's Installer by default picks up the current user during the installation, you can check [here](https://github.com/Hamza417/Inure/blob/3bb38ab492dc50841558e48ab2e1f1f4966ff5a3/app/src/main/java/app/simple/inure/viewmodels/installer/InstallerViewModel.kt#L367-L374).

**Comment by WingCH** [comment] 2023-08-28 12:54
um..
Do you have any idea about this issue?

https://github.com/Hamza417/Inure/assets/19588517/74dbf860-32d2-4594-ac8f-5f406d79f667

**Comment by Hamza417** [comment] 2023-08-28 13:44
This seems more like an app cloner of sorts, have you checked in the settings if automatic cloning is enabled or something like that, that automatically clones the newly installed apps?

**Comment by Hamza417** [comment] 2023-08-28 16:38
Because they both use the Package Manager, if I'm guessing correctly, you could try installing the APK using ADB Shell and see if the problem reproduces with the ADB as well. You can follow [this guide](https://raccoon.onyxbits.de/blog/install-split-apk-adb/) for the same. Alternatively, you can try switching to Package Installer in Inure as well and the problem should go away, however Inure automatically selects the best available framework, you might have to turn off the Root or Shizuku modes.

I ran Inure in multi-user profiles and the installer only installed for the current user in both root and non-root modes, I couldn't reproduce this issue, so you'll have to confirm it from your side.

**Comment by WingCH** [comment] 2023-08-29 12:48
```
adb devices
List of devices attached
RFCT80PB88R	device

adb shell pm list users
Users:
	UserInfo{0:wing chan :c13} running
	UserInfo{95:DUAL_APP:20001010} running
	UserInfo{150:Secure Folder:10061030} running
```

1. use `--user`, only installed on the main account
```
adb install --user 0 Downloads/FlutterUnit.apk
Performing Streamed Install
Success
```

2. without `--user` installed on main and secondary accounts
```
adb install Downloads/FlutterUnit.apk
Performing Streamed Install
Success
```

3. I can't use `pm` to install apk...should be root permission
```
pm install-write -S 11233962 1836303514 0 FlutterUnit.apk

Exception occurred while executing 'install-write':
```

4. When I disable `use Shizuku`, this problem is solved

Anyway, thanks for your help

**Comment by Hamza417** [comment] 2023-11-19 14:58
I've added an option to select users before installing the app, I'm not sure why this is happening, but based on your observation this should help fix the issue.

**Comment by Hamza417** [comment] 2024-02-10 15:29
_Show User List_ is now an official part of the app and can be toggled from **Configuration Preferences**. I've also done some improvements in [fetching the info of current user before installation that could potentially fix this issue](https://github.com/Hamza417/Inure/commit/12687f27a23ff6bb618abbef50d0e4040babfde2).

**Comment by Hamza417** [comment] 2024-02-11 13:25
Could you [test the fix in this beta build](https://github.com/Hamza417/Inure/actions/runs/7855818793) and let me know if it's fixed or not?

_Beta builds installs as a separate app and won't override any existing versions._

**Closed** 2024-02-29 21:30 UTC
Labels: bug, error
