### ISSUE TITLE
[Feature Request] Condensed appearance

### ISSUE THREAD

**Issue by sconim** [Hamza417/Inure#373] opened 2024-11-23 18:05 UTC
### Confirmation

- [X] I have read the [Code of Conduct](https://github.com/Hamza417/Inure/blob/master/CODE_OF_CONDUCT.md)
- [X] I have searched the existing issues

### Feature Description

Please consider the possibility to change app's appearance by allowing a few degrees of densities -  more condensed appearance between any two consecutive rows. I would suggest also offering fonts that would nicely integrate with this option. 

### Describe the Solution

I find the current appearance visually pleasant but too expanded/fluffy. The idea is to capture much more info on one screen. 

### Sufficiency Confirmation

- [X] I have provided all the information requested above and deemed sufficient for the developer to address the issue

**Comment by Hamza417** [comment] 2024-11-23 20:41
Could you elaborate? Is it for the grid items or the whole app?
Maybe you can refer to #21?

**Comment by sconim** [comment] 2024-11-24 18:18
> Could you elaborate? Is it for the grid items or the whole app? Maybe you can refer to #21?

For the entire app. Much like an email app where you can vary how condensed the messages are being displayed. In other words, variations of screen zooming.

**Comment by Hamza417** [comment] 2024-11-25 07:06
> For the entire app. Much like an email app where you can vary how condensed the messages are being displayed. In other words, variations of screen zooming.

Doing something like that with the whole app isn't feasible at this point but I think I can add an option to condense the main lists to show more apps in the list? Could you tell me your device's screen resolution and current density? I'd have to run the app in similar condition in the emulator to judge the problem better.

**Comment by sconim** [comment] 2024-11-25 13:04
Please see attached screenshots.
![Screenshot_20241125_080227_Device Info HW+](https://github.com/user-attachments/assets/31d6d773-92cf-4ae3-9afc-a513a84f9eda)
![Screenshot_20241125_080002_Inure](https://github.com/user-attachments/assets/fc0c5243-5eb0-4d3f-ba59-e19dba5b7760)

**Comment by Hamza417** [comment] 2024-12-06 05:03
[app-github-release.zip](https://github.com/user-attachments/files/18032924/app-github-release.zip)

I accidentally closed the issue, here is the final APK for condensed layout. Update your app and let me know what you think about all the changes so far.

**Comment by Hamza417** [comment] 2024-12-06 16:46
> The main menu & apps settings both look good. I was going to suggest condensing the main lists but then I've found out the "condensed" view option under Appearance > Layout > List styles, which now looks good.

Yes, it's added as an option to the original layout of the app.

> I've noted something's weird in the APK listing header, where the left-hand writing is vertically aligned (see attached screenshot)

That's caused by large font size, it's a different issue and not related to this one, if you want you can open a dedicated issue for that or leave it be, I'll fix it before the next release.

Everything regarding this issue is done now, so I am closing it, let me know if you find any issues later on during your regular usage of the app.

**Closed by Hamza417** 2024-12-06 16:46 UTC
Labels: feature request

**Comment by sconim** [comment] 2024-12-06 16:52
Will do, thanks!
